.TH "Quiz.klasa_zwrotna" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.klasa_zwrotna
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBscalarReturn\fP (string q)"
.br
.RI "Pobieranie z bazy pytan i odpowiedzi i wstawienie spacji aby odzielić słowa "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string Quiz\&.klasa_zwrotna\&.scalarReturn (string q)"

.PP
Pobieranie z bazy pytan i odpowiedzi i wstawienie spacji aby odzielić słowa 

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
