.TH "Quiz.Form1" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.Form1
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form, and Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm1\fP ()"
.br
.RI "Załadowanie \fBForm1\fP "
.ti -1c
.RI "\fBForm1\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Wyczyść wszystkie używane zasoby\&. "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Wyczyść wszystkie używane zasoby\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Quiz\&.Form1\&.Form1 ()"

.PP
Załadowanie \fBForm1\fP 
.SS "Quiz\&.Form1\&.Form1 ()"

.SH "Member Function Documentation"
.PP 
.SS "override void Quiz\&.Form1\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Wyczyść wszystkie używane zasoby\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP prawda, jeżeli zarządzane zasoby powinny zostać zlikwidowane; Fałsz w przeciwnym wypadku\&.
.RE
.PP

.SS "override void Quiz\&.Form1\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Wyczyść wszystkie używane zasoby\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP prawda, jeżeli zarządzane zasoby powinny zostać zlikwidowane; Fałsz w przeciwnym wypadku\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
