.TH "Quiz.koniec_gry" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.koniec_gry
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBkoniec_gry\fP ()"
.br
.RI "Załadowanie komponentów "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Quiz\&.koniec_gry\&.koniec_gry ()"

.PP
Załadowanie komponentów 
.SH "Member Function Documentation"
.PP 
.SS "override void Quiz\&.koniec_gry\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
