.TH "Quiz.Properties.Settings" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.Properties.Settings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationSettingsBase, and ApplicationSettingsBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSettings\fP \fBDefault\fP\fC [get]\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "static \fBSettings\fP Quiz\&.Properties\&.Settings\&.Default\fC [static]\fP, \fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
