.TH "Quiz.NewProgressBar" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.NewProgressBar
.SH SYNOPSIS
.br
.PP
.PP
Inherits ProgressBar, and ProgressBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewProgressBar\fP ()"
.br
.ti -1c
.RI "\fBNewProgressBar\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.ti -1c
.RI "override void \fBOnPaint\fP (PaintEventArgs e)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Quiz\&.NewProgressBar\&.NewProgressBar ()"

.SS "Quiz\&.NewProgressBar\&.NewProgressBar ()"

.SH "Member Function Documentation"
.PP 
.SS "override void Quiz\&.NewProgressBar\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"

.SS "override void Quiz\&.NewProgressBar\&.OnPaint (PaintEventArgs e)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
