.TH "Quiz/QUIZ.cs" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz/QUIZ.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuiz\&.QUIZ\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBQuiz\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
