.TH "Quiz.QUIZ" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz.QUIZ
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form, and Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQUIZ\fP ()"
.br
.ti -1c
.RI "\fBQUIZ\fP ()"
.br
.RI "Komponenty "
.ti -1c
.RI "void \fBtab_zmian\fP (int P)"
.br
.RI "Tablica z wygranymi jeżeli odpowiemy na pytanie przechodzi do kolejnego "
.ti -1c
.RI "void \fBfunkcja_przyciskow\fP ()"
.br
.RI "funkcja przycisków "
.ti -1c
.RI "void \fBwys_pytanie\fP (int id_pytania)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBwynik\fP"
.br
.RI "Wyniku "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Quiz\&.QUIZ\&.QUIZ ()"

.SS "Quiz\&.QUIZ\&.QUIZ ()"

.PP
Komponenty 
.SH "Member Function Documentation"
.PP 
.SS "override void Quiz\&.QUIZ\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "override void Quiz\&.QUIZ\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "void Quiz\&.QUIZ\&.funkcja_przyciskow ()"

.PP
funkcja przycisków sprawdzanie odpowiedzi 
.PP
losowanie pytania z bazy danych 
.PP
jeżeli sie pomylimy to koniec gry 
.SS "void Quiz\&.QUIZ\&.tab_zmian (int P)"

.PP
Tablica z wygranymi jeżeli odpowiemy na pytanie przechodzi do kolejnego 
.SS "void Quiz\&.QUIZ\&.wys_pytanie (int id_pytania)"
łączenie z baza danych, pobieranie pytań i odpowiedzi 
.SH "Member Data Documentation"
.PP 
.SS "string Quiz\&.QUIZ\&.wynik\fC [static]\fP"

.PP
Wyniku 

.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
