.TH "Quiz/Quiz/Properties/Resources.Designer.cs" 3 "Sun Jun 30 2019" "Quiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quiz/Quiz/Properties/Resources.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuiz\&.Properties\&.Resources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBQuiz\fP"
.br
.ti -1c
.RI "namespace \fBQuiz\&.Properties\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Quiz from the source code\&.
